>link
#Link
AT_agc072_a;https://atcoder.jp/contests/agc072/tasks/agc072_a
#Code
code;?file=code0.cpp
<link

>df
2800
<df

>tag
DP
<tag

>sub
2026-04-16 08:18:45;AT_agc072_a;https://atcoder.jp/contests/agc072/submissions/74988452
<sub