>link
#Link
AT_pakencamp_2024_day2_b;https://atcoder.jp/contests/pakencamp-2024-day2/tasks/pakencamp_2024_day2_b
#Code
code;?file=code0.cpp
<link

>df
2800
<df

>tag
DP
换根DP
<tag

>sub
2026-07-10 11:45:08;AT_pakencamp_2024_day2_b;https://atcoder.jp/contests/pakencamp-2024-day2/submissions/77313637
<sub