>link
#Link
AT_arc217_d;https://atcoder.jp/contests/arc217/tasks/arc217_d
#Code
code;?file=code0.cpp
<link

>df
2700
<df

>tag
势能分析
单调栈
<tag

>sub
2026-04-22 15:40:52;AT_arc217_d;https://atcoder.jp/contests/arc217/submissions/75164526
<sub