>link
#Link
AT_abc249_h;https://atcoder.jp/contests/abc249/tasks/abc249_h
#Code
code;?file=code0.cpp
<link

>df
3300
<df

>tag
停时问题
<tag

>sub
2026-06-17 14:28:32;AT_abc249_h;https://atcoder.jp/contests/abc249/submissions/76741214
<sub