>link
#Link
CF2156F2
#Easy
CF2156F1
#Code
code;?file=code0.cpp
<link

>df
3000
<df

>tag
贪心
数据结构
势能分析
<tag

>sub
2026-04-22 09:16:01;CF2156F2;https://codeforces.com/contest/2156/submission/372086258
<sub