>link
#Link
AT_arc217_b;https://atcoder.jp/contests/arc217/tasks/arc217_b
#Code
code;?file=code0.cpp
<link

>df
1900
<df

>tag
ad-hoc
<tag

>sub
2026-04-22 08:24:32;AT_arc217_b;https://atcoder.jp/contests/arc217/submissions/75158237
<sub