>link
#Link
AT_awtf2026algo_a;https://atcoder.jp/contests/awtf2026algo-open/tasks/awtf2026algo_a
#Code
code;?file=code0.cpp
<link

>df
2900
<df

>tag
贪心
Kruscal重构树
<tag

>sub
2026-07-09 11:24:21;AT_awtf2026algo_a;https://atcoder.jp/contests/awtf2026algo-open/submissions/77295507
<sub